smiles = [
    ("OCC", True),
    ("CCO", True),
    ("[CH3][CH2][OH]", True),
    ("CCO", True),
    ("C-C-O", True),
    ("CCO", True),
    ("C(O)C", True),
    ("CCO", True),
    ("OC(=O)C(Br)(Cl)N", True),
    ("NC(Cl)(Br)C(=O)O", True),
    ("ClC(Br)(N)C(=O)O", True),
    ("NC(Cl)(Br)C(=O)O", True),
    ("O=C(O)C(N)(Br)Cl", True),
    ("NC(Cl)(Br)C(=O)O", True),
    ("[H+]", True),
    ("[Fe+2]", True),
    ("[OH-]", True),
    ("[Fe++]", True),
    ("[OH3+]", True),
    ("[NH4+]", True),
    ("CC", True),
    ("C=O", True),
    ("C=C", True),
    ("O=C=O", True),
    ("COC", True),
    ("C#N", True),
    ("CCO", True),
    ("[H][H]", True),
    ("C=CC(CCC)C(C(C)C)CCC", True),
    ("O1CCCCC1N1CCCCC1", True),
    # FIXME need to support this
    # ("F/C=C/C=C/C", True),
    # ("F/C=CF", False),
    ("F/C=C/F", True),
    ("F/C=C\\F", True),
    ("N[C@](C)(F)C(=O)O", True),
    ("N[C@@](F)(C)C(=O)O", True),
    ("N[C@@]([H])(C)C(=O)O", True),
    ("N[C@]([H])(C)C(=O)O", True),
    ("N[C@@H](C)C(=O)O", True),
    ("N[C@H](C)C(=O)O", True),
    ("N[C@H](C(=O)O)C", True),
    ("N[C@@H](C(=O)O)C", True),
    ("[H][C@](N)(C)C(=O)O", True),
    ("[H][C@@](N)(C)C(=O)O", True),
    ("[C@H](N)(C)C(=O)O", True),
    ("[C@@H](N)(C)C(=O)O", True),
    ("C1=CN=C[NH]C(=O)1", True),
    ("c1cnc[nH]c(=O)1", True),
    ("O=n1ccccc1", True),
    ("[O-][n+]1ccccc1", True),
    ("O=c1[nH]cccc1", True),
    ("[15NH3+]", True),
    ("[15NH3-]", True),
    ("C1CCC2CCC12", True),
    ("C1CCC%12CCC1%12", True),
    ("H", False),
    ("C-C-C-C", True),
    ("C-[C-3]", True),
    ("C12C3C4C1C5C4C3C25", True),
]


parser_tests = [
    ("C", True),
    ("CCCCC", True),
    # dropped support for this now
    # ("CCC.CC.CCC.CCC", True),
    ("CC-C=CC#C:C", True),
    ("C12C3C4C1C5C4C3C25", True),
    ("C1CCCC2", False),
    ("CCC=", False),
    ("CCC/", False),
    ("=CCC", False),
    ("[N+]CC", True),
    ("F[Si--](F)(F)(F)(F)F", True),
    ("F[Si-2](F)(F)(F)(F)F", True),
    ("F[Si-+](F)(F)(F)(F)F", False),
]
